name: Linux Build

on:
  workflow_dispatch:
    inputs:    
      increaseVersion:
        description: 'increase version - yes/no' 
        default: "yes"
      # deployTo:
      #   description: 'comma separated list of envs to deploy'
  push:
    branches: ['*']
    tags-ignore:
    - build-*

jobs:
  build:
    if: ${{ ( github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '#build') || (github.ref  == 'refs/heads/main') || (github.ref  == 'refs/heads/master')) && !contains(github.event.head_commit.message, '#skip-build') }}
    runs-on: ubuntu-latest

    steps:
    - name: Set Repo Envs
      run: |
        REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
        echo "git_repo_name=${REPO_NAME}" | tee -a $GITHUB_ENV
        echo ""

    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
        versionSpec: '5.8.1'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.11

    - name: set version
      run: |
        GITVERSION=${{ steps.gitversion.outputs.fullSemVer }}
        echo "gitversion=${GITVERSION}" | tee -a $GITHUB_ENV

    - name: python build
      env:
        VERSION: ${{ env.gitversion }}
      run: |
        pip install pyinstaller
        pyinstaller --onefile getos.py

    - name: commit-tag-build
      if: ${{ !env.ACT }}
      env:
        TAG: ${{ env.gitversion }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git tag "${TAG}" || true
        git push --tags

    
    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/getos